package io.omnibrige.config;

import io.omnibrige.core.ConfigManager;

import java.io.File;

public class FloodgateConfig {

    public File generate(File pluginsDir) {
        File configDir = new File(pluginsDir, "floodgate");
        File configFile = new File(configDir, "config.yml");

        String content = """
                # Floodgate Configuration (generated by OmniBridge)
                key-file-name: key.pem
                username-prefix: "."
                replace-spaces: true
                disconnect:
                  invalid-key: 'Please connect through the official Geyser'
                  invalid-arguments-length: 'Expected {} arguments, got {}. Is Geyser up-to-date?'
                player-link:
                  enabled: true
                  require-link: false
                  enable-own-linking: false
                  allowed: true
                  link-code-timeout: 300
                  type: sqlite
                  enable-global-linking: true
                metrics:
                  enabled: true
                """;

        ConfigManager.writeConfigFile(configFile, content);
        return configFile;
    }
}
