/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * OmniBridge - Universal cross-version and cross-platform connectivity
 * Copyright (c) 2026 OmniBridge Contributors
 */

package io.omnibrige.config;

import io.omnibrige.core.ConfigManager;

import java.io.File;

/**
 * Generates the Floodgate config.yml with default Bedrock proxy settings.
 */
public class FloodgateConfig {

    /**
     * Generates the Floodgate config.yml file if it does not already exist.
     *
     * @param pluginsDir the root plugins directory
     * @return the generated config file
     */
    public File generate(File pluginsDir) {
        File configDir = new File(pluginsDir, "floodgate");
        File configFile = new File(configDir, "config.yml");

        String content = """
                # Floodgate Configuration (generated by OmniBridge)
                port: 19132
                send-floodgate-data: true
                player-linking: true
                bedrock-language: en_us
                log-player-ip-addresses: true
                enforce-primary-account: true
                """;

        ConfigManager.writeConfigFile(configFile, content);
        return configFile;
    }
}
