package io.omnibrige.config;

import io.omnibrige.core.ConfigManager;

import java.io.File;

public class FloodgateConfig {

    public File generate(File pluginsDir) {
        File configDir = new File(pluginsDir, "floodgate");
        File configFile = new File(configDir, "config.yml");

        String content = """
                # Floodgate Configuration (generated by OmniBridge)
                port: 19132
                send-floodgate-data: true
                player-linking: true
                bedrock-language: en_us
                log-player-ip-addresses: true
                enforce-primary-account: true
                """;

        ConfigManager.writeConfigFile(configFile, content);
        return configFile;
    }
}
