/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * OmniBridge - Universal cross-version and cross-platform connectivity
 * Copyright (c) 2026 OmniBridge Contributors
 */

package io.omnibrige.config;

import io.omnibrige.core.ConfigManager;
import org.bukkit.configuration.file.FileConfiguration;

import java.io.File;

/**
 * Generates the Geyser config.yml with address and port settings inherited from OmniBridge config.
 */
public class GeyserConfig {

    private final FileConfiguration omnibrigeConfig;

    /**
     * Constructs the Geyser config generator.
     *
     * @param omnibrigeConfig the OmniBridge configuration to read address/port values from
     */
    public GeyserConfig(FileConfiguration omnibrigeConfig) {
        this.omnibrigeConfig = omnibrigeConfig;
    }

    /**
     * Generates the Geyser config.yml file if it does not already exist.
     *
     * @param pluginsDir the root plugins directory
     * @return the generated config file
     */
    public File generate(File pluginsDir) {
        File configDir = new File(pluginsDir, "Geyser-Spigot");
        File configFile = new File(configDir, "config.yml");

        String bedrockAddress = omnibrigeConfig.getString("bedrock.address", "0.0.0.0");
        int bedrockPort = omnibrigeConfig.getInt("bedrock.port", 19132);
        String javaAddress = omnibrigeConfig.getString("java.address", "127.0.0.1");
        int javaPort = omnibrigeConfig.getInt("java.port", 25565);

        String content = """
                # Geyser Configuration (generated by OmniBridge)
                bedrock:
                  address: %s
                  port: %d
                  clone-remote-port: false
                  motd1: 'A Geyser Powered Server'
                  motd2: 'A Geyser Powered Server'
                  motd3: 'A Geyser Powered Server'
                  server-name: 'Geyser Server'
                  server-name-type: motd
                floodgate-key-file: key.pem
                remote:
                  address: %s
                  port: %d
                  auth-type: floodgate
                  allow-cache-password: false
                metrics:
                  enabled: true
                  uuid: auto
                user:
                  add-advanced-tooltips: false
                  show-cooldown-seconds: true
                  show-coordinate-uv: true
                  disable-cell-shading: false
                  cursor-sharing: true
                  skin-remapping: true
                general:
                  chat-type: CHAT
                  emote-offhand: false
                  movement:
                    emote-cache: true
                    item-drop-movement: true
                    vehicle-movement: true
                extended-world-height: true
                allow-third-party-capes: true
                allow-third-party-ears: false
                third-party-cosmetics:
                  allowed-cosmetics: []
                default-language: en_us
                log-player-ip-addresses: true
                debug-mode: false
                """;

        content = String.format(content, bedrockAddress, bedrockPort, javaAddress, javaPort);
        ConfigManager.writeConfigFile(configFile, content);
        return configFile;
    }
}
