package io.omnibrige.config;

import io.omnibrige.core.ConfigManager;

import java.io.File;

public class ViaBackwardsConfig {

    public File generate(File pluginsDir) {
        File configDir = new File(pluginsDir, "ViaBackwards");
        File configFile = new File(configDir, "config.yml");

        String content = """
                # ViaBackwards Configuration (generated by OmniBridge)
                log-level: INFO
                add-1_14-shulker: true
                only-show-custom-protocol-items: false
                """;

        ConfigManager.writeConfigFile(configFile, content);
        return configFile;
    }
}
