package io.omnibrige.config;

import io.omnibrige.core.ConfigManager;

import java.io.File;

public class ViaBackwardsConfig {

    public File generate(File pluginsDir) {
        File configDir = new File(pluginsDir, "ViaBackwards");
        File configFile = new File(configDir, "config.yml");

        String content = """
                # ViaBackwards Configuration (generated by OmniBridge)
                add-custom-enchants-to-lore: false
                add-team-color-to-1_13-prefix: false
                fix-1_13-face-player: false
                fix-1_13-formatted-inventory-title: false
                always-show-original-mob-name: false
                handle-pings-as-inv-acknowledgements: false
                bedrock-at-y0: false
                sculk-shrieker-to-crying-obsidian: false
                scaffolding-to-water: false
                map-darkness-effect: false
                map-custom-model-data: false
                map-display-entities: false
                suppress-emulation-warnings: false
                """;

        ConfigManager.writeConfigFile(configFile, content);
        return configFile;
    }
}
