/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * OmniBridge - Universal cross-version and cross-platform connectivity
 * Copyright (c) 2026 OmniBridge Contributors
 */

package io.omnibrige.config;

import io.omnibrige.core.ConfigManager;

import java.io.File;

/**
 * Generates the ViaBackwards config.yml with default backward-compatibility settings.
 */
public class ViaBackwardsConfig {

    /**
     * Generates the ViaBackwards config.yml file if it does not already exist.
     *
     * @param pluginsDir the root plugins directory
     * @return the generated config file
     */
    public File generate(File pluginsDir) {
        File configDir = new File(pluginsDir, "ViaBackwards");
        File configFile = new File(configDir, "config.yml");

        String content = """
                # ViaBackwards Configuration (generated by OmniBridge)
                log-level: INFO
                add-1_14-shulker: true
                only-show-custom-protocol-items: false
                """;

        ConfigManager.writeConfigFile(configFile, content);
        return configFile;
    }
}
