package io.omnibrige.config;

import io.omnibrige.core.ConfigManager;

import java.io.File;

public class ViaRewindConfig {

    public File generate(File pluginsDir) {
        File configDir = new File(pluginsDir, "ViaRewind");
        File configFile = new File(configDir, "config.yml");

        String content = """
                # ViaRewind Configuration (generated by OmniBridge)
                cooldown-indicator: TITLE
                replace-adventure-mode: false
                replace-particles: false
                max-book-pages: 100
                max-book-page-size: 5000
                emulate-world-border: true
                always-show-original-mob-name: false
                world-border-particle: iconcrack
                enable-offhand: false
                offhand-command: offhand
                emulate-levitation-effect: true
                handle-player-combat-packet: true
                """;

        ConfigManager.writeConfigFile(configFile, content);
        return configFile;
    }
}
