package io.omnibrige.config;

import io.omnibrige.core.ConfigManager;

import java.io.File;

public class ViaRewindConfig {

    public File generate(File pluginsDir) {
        File configDir = new File(pluginsDir, "ViaRewind");
        File configFile = new File(configDir, "config.yml");

        String content = """
                # ViaRewind Configuration (generated by OmniBridge)
                log-level: INFO
                """;

        ConfigManager.writeConfigFile(configFile, content);
        return configFile;
    }
}
