/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * OmniBridge - Universal cross-version and cross-platform connectivity
 * Copyright (c) 2026 OmniBridge Contributors
 */

package io.omnibrige.config;

import io.omnibrige.core.ConfigManager;

import java.io.File;

public class ViaRewindLegacySupportConfig {

    public File generate(File pluginsDir) {
        File configDir = new File(pluginsDir, "ViaRewindLegacySupport");
        File configFile = new File(configDir, "config.yml");

        String content = """
                # ViaRewind LegacySupport Configuration (generated by OmniBridge)
                # Lily Pad bounding box fix
                lily-pad: true
                # Ladder bounding box fix
                ladder: true
                # Enchantment Table lapis fix
                enchantment-table: true
                # Brewing Stand interaction fix
                brewing-stand: true
                # Block placement and item pickup sounds
                sounds: true
                # Elytra flight velocity
                elytra: true
                # Slime Block bouncing
                slime-block: true
                # AreaEffectCloud visibility
                area-effect-cloud: true
                """;

        ConfigManager.writeConfigFile(configFile, content);
        return configFile;
    }
}
