/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * OmniBridge - Universal cross-version and cross-platform connectivity
 * Copyright (c) 2026 OmniBridge Contributors
 */

package io.omnibrige.config;

import io.omnibrige.core.ConfigManager;

import java.io.File;

/**
 * Generates the ViaVersion config.yml with recommended cross-version settings.
 */
public class ViaVersionConfig {

    /**
     * Generates the ViaVersion config.yml file if it does not already exist.
     *
     * @param pluginsDir the root plugins directory
     * @return the generated config file
     */
    public File generate(File pluginsDir) {
        File configDir = new File(pluginsDir, "ViaVersion");
        File configFile = new File(configDir, "config.yml");

        String content = """
                # ViaVersion Configuration (generated by OmniBridge)
                blockconnectionsserverside: true
                preferviaversion: -1
                nms-player-ticking: true
                blockconnectionslow: false
                anti-block-incompat: false
                velocity-support:
                  enabled: false
                  secret: ''
                  online-mode: true
                compat:
                 hover-clip: true
                block-id-resend: true
                percent-blocking: 0.0
                main-command: viaver
                auto-team: true
                forced-use-version: ''
                block-connections:
                  enabled: true
                  threshold: 3
                  world-changing: true
                suppress-conversion-warnings: false
                log-level: INFO
                packet-pps-limit:
                  enabled: false
                  max-pps: -1
                  kick-message: ''
                """;

        ConfigManager.writeConfigFile(configFile, content);
        return configFile;
    }
}
