package io.omnibrige.config;

import io.omnibrige.core.ConfigManager;

import java.io.File;

public class ViaVersionConfig {

    public File generate(File pluginsDir) {
        File configDir = new File(pluginsDir, "ViaVersion");
        File configFile = new File(configDir, "config.yml");

        String content = """
                # ViaVersion Configuration (generated by OmniBridge)
                blockconnectionsserverside: true
                preferviaversion: -1
                nms-player-ticking: true
                blockconnectionslow: false
                anti-block-incompat: false
                velocity-support:
                  enabled: false
                  secret: ''
                  online-mode: true
                compat:
                 hover-clip: true
                block-id-resend: true
                percent-blocking: 0.0
                main-command: viaver
                auto-team: true
                forced-use-version: ''
                block-connections:
                  enabled: true
                  threshold: 3
                  world-changing: true
                suppress-conversion-warnings: false
                log-level: INFO
                packet-pps-limit:
                  enabled: false
                  max-pps: -1
                  kick-message: ''
                """;

        ConfigManager.writeConfigFile(configFile, content);
        return configFile;
    }
}
