package io.omnibrige.config;

import io.omnibrige.core.ConfigManager;

import java.io.File;

public class ViaVersionConfig {

    public File generate(File pluginsDir) {
        File configDir = new File(pluginsDir, "ViaVersion");
        File configFile = new File(configDir, "config.yml");

        String content = """
                # ViaVersion Configuration (generated by OmniBridge)
                check-for-updates: true
                send-supported-versions: false
                block-protocols: []
                block-versions: []
                block-disconnect-msg: 'You are using an unsupported Minecraft version!'
                reload-disconnect-msg: 'Server reload, please rejoin!'
                logging:
                  log-blocked-joins: false
                  log-entity-data-errors: true
                  log-text-component-conversion-errors: false
                  log-other-conversion-warnings: false
                  max-error-length: 1500
                packet-limiter:
                  enabled: true
                  max-per-second: 800
                  max-per-second-kick-message: 'You are sending too many packets!'
                  sustained-max-per-second: 150
                  sustained-period-seconds: 7
                  sustained-threshold: 4
                  sustained-kick-message: 'You are sending too many packets, :('
                packet-size-limiter:
                  enabled: false
                simulate-pt: true
                nms-player-ticking: true
                auto-team: true
                prevent-collision: true
                shield-blocking: true
                no-delay-shield-blocking: false
                show-shield-when-sword-in-hand: false
                bossbar-patch: true
                bossbar-anti-flicker: false
                hologram-patch: false
                hologram-y: -0.96
                piston-animation-patch: false
                use-new-effect-indicator: true
                use-new-deathmessages: true
                item-cache: true
                serverside-blockconnections: true
                reduce-blockstorage-memory: false
                left-handed-handling: true
                team-colour-fix: true
                truncate-1_14-books: false
                fix-infested-block-breaking: true
                fix-low-snow-collision: false
                fix-non-full-blocklight: false
                fix-1_14-health-nan: true
                use-1_15-instant-respawn: false
                ignore-long-1_16-channel-names: true
                cache-1_17-light: true
                enforce-secure-chat: false
                handle-invalid-item-count: false
                cancel-block-sounds: true
                hide-scoreboard-numbers: false
                fix-1_21-placement-rotation: true
                cancel-swing-in-inventory: true
                use-1_8-hitbox-margin: true
                send-player-details: true
                send-server-details: true
                """;

        ConfigManager.writeConfigFile(configFile, content);
        return configFile;
    }
}
